[package]
name = "serde-basic"
version = "0.1.0"
authors = ["fujidori <fujidori9@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
serde_yaml = "0.8.8"
